# Generated by Django 4.2.30 on 2026-05-28 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('total_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Всего недель')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название (напр. 9А)')),
                ('grade_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Номер класса')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Уровень образования')),
                ('shift_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Смена')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schedule_app.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='ClassSpecialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специализация класса',
                'verbose_name_plural': 'Специализации классов',
            },
        ),
        migrations.CreateModel(
            name='ClassSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во учеников')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='schedule_app.classgroup', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ранг')),
                ('tabel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Таблица')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер/название')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('is_specialized', models.BooleanField(default=False, verbose_name='Специализированный')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='SanpinLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс от')),
                ('grade_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Класс до')),
                ('max_periods_5day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. уроков (5-дн.)')),
                ('max_periods_6day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. уроков (6-дн.)')),
                ('lesson_duration_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. длит. урока (мин)')),
            ],
            options={
                'verbose_name': 'Ограничение СанПиН',
                'verbose_name_plural': 'Ограничения СанПиН',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('week_days_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(6)])),
                ('shift_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('fgos_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область ФГОС')),
                ('is_elective', models.BooleanField(default=False, verbose_name='Элективный')),
                ('difficulty_rank', models.ForeignKey(blank=True, db_column='difficulty_rank', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_app.difficultylevel', verbose_name='Уровень сложности')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип каникул',
                'verbose_name_plural': 'Типы каникул',
            },
        ),
        migrations.CreateModel(
            name='VacationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('is_extra', models.BooleanField(default=False, verbose_name='Дополнительные')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_periods', to='schedule_app.academicyear', verbose_name='Учебный год')),
                ('vacation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.vacationtype', verbose_name='Тип каникул')),
            ],
            options={
                'verbose_name': 'Каникулы',
                'verbose_name_plural': 'Каникулы',
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='День недели (1=Пн)')),
                ('period_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер урока')),
                ('date_from', models.DateField(verbose_name='С')),
                ('date_to', models.DateField(verbose_name='По')),
                ('unavailability_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='schedule_app.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Недоступность учителя',
                'verbose_name_plural': 'Недоступность учителей',
            },
        ),
        migrations.CreateModel(
            name='SubjectRoomRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_room_type', models.CharField(max_length=100, verbose_name='Требуемый тип кабинета')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_requirements', to='schedule_app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Требование к кабинету',
                'verbose_name_plural': 'Требования к кабинетам',
            },
        ),
        migrations.CreateModel(
            name='RoomUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='С')),
                ('date_to', models.DateField(verbose_name='По')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='schedule_app.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Недоступность кабинета',
                'verbose_name_plural': 'Недоступность кабинетов',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedule_app.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='class_specialisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule_app.classspecialisation', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schedule_app.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер смены')),
                ('period_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер урока')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('break_after_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Перемена после (мин)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bell_schedules', to='schedule_app.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
                'ordering': ['shift_number', 'period_number'],
            },
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schedule_app.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной предмет')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schedule_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schedule_app.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Предмет учителя',
                'verbose_name_plural': 'Предметы учителей',
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours_norm', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Норма часов/неделю')),
                ('weekly_hours_max', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Макс. часов/неделю')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schedule_app.school', verbose_name='Школа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='schedule_app.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Учитель в школе',
                'verbose_name_plural': 'Учителя в школах',
                'unique_together': {('teacher', 'school')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='День недели (1=Пн)')),
                ('period_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер урока')),
                ('week_parity', models.IntegerField(choices=[(0, 'Обе недели'), (1, 'Нечётная'), (2, 'Чётная')], default=0, verbose_name='Чётность недели')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('is_substitution', models.BooleanField(default=False, verbose_name='Замена')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.academicyear', verbose_name='Учебный год')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.classgroup', verbose_name='Класс')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.room', verbose_name='Кабинет')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.classsubgroup', verbose_name='Подгруппа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='schedule_app.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Урок в расписании',
                'verbose_name_plural': 'Расписание',
                'unique_together': {('class_group', 'subgroup', 'day_of_week', 'period_number', 'week_parity', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Часов в неделю')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('semester', models.CharField(choices=[('autumn', 'Осень'), ('spring', 'Весна'), ('full_year', 'Весь год')], max_length=10, verbose_name='Семестр')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='schedule_app.classgroup', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='schedule_app.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'unique_together': {('class_group', 'subject', 'semester')},
            },
        ),
    ]
