# Generated by Django 4.2.30 on 2026-05-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['school', 'start_date'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['school', 'academic_year', 'grade_number', 'name'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='classspecialisation',
            options={'ordering': ['name'], 'verbose_name': 'Специализация класса', 'verbose_name_plural': 'Специализации классов'},
        ),
        migrations.AlterModelOptions(
            name='classsubgroup',
            options={'ordering': ['class_group', 'name'], 'verbose_name': 'Подгруппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterModelOptions(
            name='curriculumplan',
            options={'ordering': ['class_group', 'subject', 'semester'], 'verbose_name': 'Учебный план', 'verbose_name_plural': 'Учебные планы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['school', 'number'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='roomunavailability',
            options={'ordering': ['room', 'date_from'], 'verbose_name': 'Недоступность кабинета', 'verbose_name_plural': 'Недоступность кабинетов'},
        ),
        migrations.AlterModelOptions(
            name='sanpinlimit',
            options={'ordering': ['grade_from'], 'verbose_name': 'Ограничение СанПиН', 'verbose_name_plural': 'Ограничения СанПиН'},
        ),
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ['academic_year', 'class_group', 'day_of_week', 'period_number'], 'verbose_name': 'Урок в расписании', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'Школа', 'verbose_name_plural': 'Школы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='subjectroomrequirement',
            options={'ordering': ['subject', 'required_room_type'], 'verbose_name': 'Требование к кабинету', 'verbose_name_plural': 'Требования к кабинетам'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='teacherschool',
            options={'ordering': ['school', 'teacher'], 'verbose_name': 'Учитель в школе', 'verbose_name_plural': 'Учителя в школах'},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['teacher', 'subject'], 'verbose_name': 'Предмет учителя', 'verbose_name_plural': 'Предметы учителей'},
        ),
        migrations.AlterModelOptions(
            name='teacherunavailability',
            options={'ordering': ['teacher', 'date_from'], 'verbose_name': 'Недоступность учителя', 'verbose_name_plural': 'Недоступность учителей'},
        ),
        migrations.AlterModelOptions(
            name='vacationperiod',
            options={'ordering': ['academic_year', 'start_date'], 'verbose_name': 'Каникулы', 'verbose_name_plural': 'Каникулы'},
        ),
        migrations.AlterModelOptions(
            name='vacationtype',
            options={'ordering': ['title'], 'verbose_name': 'Тип каникул', 'verbose_name_plural': 'Типы каникул'},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curriculumplan',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='schedule_app.classsubgroup', verbose_name='Подгруппа'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumplan',
            unique_together={('class_group', 'subgroup', 'subject', 'semester')},
        ),
    ]
